name: autodiff

{% set python_version = os.environ.get("PYTHON_VERSION", "3.12") %}

channels:
  - conda-forge
  - nvidia

dependencies:
  - catch2>=3
  - ccache
  - clangxx  # [linux]
  - clangxx_osx-64  # [osx and not arm64]
  - clangxx_osx-arm64  # [osx and arm64]
  - cmake
  - doxygen=1.9.1  # [linux]
  - eigen
  - git
  - graphviz  # [linux]
  - gxx_linux-64  # [linux]
  - lld  # [linux]
  - make  # [unix]
  - mkdocs
  - mkdocs-macros-plugin
  - mkdocs-material
  - ninja
  - pip
  - pre-commit
  - pybind11
  - pybind11-abi
  - pybind11-stubgen
  - python={{ python_version }}
  - setuptools
  - shellcheck
  - vs2019_win-64  # [win]
  - cuda-toolkit  # [linux]
  - cuda-toolkit  # [windows]
